#SPDX-License-Identifier: MIT-0
---
- name: Instalar paquetes nginx
  apt:
    name: "{{ packages_loadbalancer }}"
    state: present

- name: Configurar nginx
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/wordpress.conf
  notify: restart nginx

- name: Habilitar sitio nginx
  file:
    src: /etc/nginx/sites-available/wordpress.conf 
    dest: /etc/nginx/sites-enabled/wordpress.conf
    state: link
  notify: restart nginx

- name: Eliminar sitio por defecto de nginx
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: restart nginx

- name: Asegurar que nginx esté en ejecución
  service:
    name: nginx
    state: started
    enabled: true
