#Docker Compose file for Ansible inventory dev-hosts.ini
services:
  ansible:
    image: guillemhs/ansible-node-systemd:latest
    container_name: ansible
    hostname: ansible
    networks:
      ansible-net:
        ipv4_address: 10.11.12.10
    volumes:
      - ./ssh:/home/vagrant/.ssh/host_keys
      - .:/home/vagrant/workspace
    tmpfs:
      - /run
      - /run/lock
      - /tmp
    stdin_open: true
    tty: true
    privileged: true
    dns:
      - 8.8.8.8
      - 8.8.4.4
    cap_add:
      - NET_ADMIN

  database:
    image: guillemhs/ansible-node-systemd:latest
    container_name: database
    hostname: database
    networks:
      ansible-net:
        ipv4_address: 10.11.12.20
    ports:
      - "3306:3306"
      - "2220:22"
    tmpfs:
      - /run
      - /run/lock
      - /tmp
    stdin_open: true
    tty: true
    privileged: true
    dns:
      - 8.8.8.8
      - 8.8.4.4
    cap_add:
      - NET_ADMIN

  loadbalancer:
    image: guillemhs/ansible-node-systemd:latest
    container_name: loadbalancer
    hostname: loadbalancer
    networks:
      ansible-net:
        ipv4_address: 10.11.12.30
    ports:
      - "8080:80"
      - "2221:22"
    tmpfs:
      - /run
      - /run/lock
      - /tmp
    stdin_open: true
    tty: true
    privileged: true
    dns:
      - 8.8.8.8
      - 8.8.4.4
    cap_add:
      - NET_ADMIN

  webserver:
    image: guillemhs/ansible-node-systemd:latest
    container_name: webserver
    hostname: webserver
    networks:
      ansible-net:
        ipv4_address: 10.11.12.40
    ports:
      - "80:80"
      - "2222:22"
    tmpfs:
      - /run
      - /run/lock
      - /tmp
    stdin_open: true
    tty: true
    privileged: true
    dns:
      - 8.8.8.8
      - 8.8.4.4
    cap_add:
      - NET_ADMIN

networks:
  ansible-net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.11.12.0/24
          gateway: 10.11.12.1