---
- hosts: database
  become: true
  vars_files:
    - group_vars/all.yml
  roles:
    - mysql

- hosts: webserver
  become: true
  vars_files:
    - group_vars/all.yml  
  roles:
    - apache2
    - php
    - wordpress

- hosts: loadbalancer
  become: true
  roles:
    - nginx