---
- hosts: database
  become: true
  vars_files:
    - group_vars/all.yml
  roles:
    - mysql

- hosts: loadbalancer
  become: true
  roles:
    - nginx

- hosts: webserver
  become: true
  roles:
    - php
    - wordpress
    - apache2